#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RS_SHOP_Dev.Droid.Resource", IsApplication=true)]

namespace RS_SHOP_Dev.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorAppText = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimary = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int colorPrimaryDark = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int launcher_background = 2130771972;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020003
			public const int arrow = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int buttonChecked = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int buttonUnChecked = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int camera3 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int cart = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int check = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int close = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int delete = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int edit = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int fb = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int filter2 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int floating = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int gallery = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int gp = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int greater = 2130837521;
			
			// aapt resource value: 0x7F020000
			public const int Home = 2130837504;
			
			// aapt resource value: 0x7F020012
			public const int hometab = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int ic_clear_icon = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int location = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int @lock = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int mail = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int notification = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int orders = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int payment = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int qanda = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int qrcode = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int radiobutton = 2130837532;
			
			// aapt resource value: 0x7F020001
			public const int Rarrow = 2130837505;
			
			// aapt resource value: 0x7F02001D
			public const int search = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int share = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int smart = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int ticket = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int tw = 2130837537;
			
			// aapt resource value: 0x7F020002
			public const int User = 2130837506;
			
			// aapt resource value: 0x7F020022
			public const int user1 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int wallet = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int wishlist = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int @lock = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int mail = 2131034116;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int facebook_app_id = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int facebook_app_name = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int fb_login_protocol_scheme = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int AppCompatDialogStyle = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int MainTheme = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int MainTheme_Base = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int MyTabLayout = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int MyTabTextAppearance = 2131165188;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F080000
			public const int file_paths = 2131230720;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
