//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ECOMM_DELIVERY_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ECOMM_DELIVERY_TYPE()
        {
            this.TB_ECOMM_ORDER = new HashSet<TB_ECOMM_ORDER>();
        }
    
        public long DELIVERY_TYPE_ID { get; set; }
        public string DELIVERY_TYPE_NAME { get; set; }
        public Nullable<decimal> DELIVERY_TYPE_COST { get; set; }
        public string STORE_ADDRESS1 { get; set; }
        public string STORE_ADDRESS2 { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ECOMM_ORDER> TB_ECOMM_ORDER { get; set; }
    }
}
