//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ECOMM_CARD_DETAILS
    {
        public long CARD_ID { get; set; }
        public Nullable<long> CARD_NUMBER { get; set; }
        public string CARD_HOLDER_NAME { get; set; }
        public string CARD_EXP_DATE { get; set; }
        public string CARD_TYPE { get; set; }
        public string CARD_CVV { get; set; }
        public string UDF_1 { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<bool> CARD_DEFAULT { get; set; }
    
        public virtual TB_ECOMM_USERS TB_ECOMM_USERS { get; set; }
    }
}
