//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ECOMM_PRODUCT_DETAILS
    {
        public long PRODUCT_DETAIL_ID { get; set; }
        public Nullable<long> PRODUCT_ID { get; set; }
        public string PRODUCT_SIZE { get; set; }
        public string PRODUCT_COLOR { get; set; }
        public string PRODUCT_QR_TAG { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual TB_ECOMM_PRODUCT TB_ECOMM_PRODUCT { get; set; }
    }
}
