//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ECOMM_PAYMENT_STATUS_DETAILS
    {
        public long PAYMENT_STATUS_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public string TIMESTAMP { get; set; }
        public string MERCHANT_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string ORDER_ID { get; set; }
        public string AUTH_CODE { get; set; }
        public string RESULT { get; set; }
        public string CVN_RESULT { get; set; }
        public string AVS_ADDRESS_RESPONSE { get; set; }
        public string BATCH_ID { get; set; }
        public string MESSAGE { get; set; }
        public string PAYMENT_REF_NUMBER { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_COUNTRY { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string REGION { get; set; }
        public string SHA_HASH { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual TB_ECOMM_USERS TB_ECOMM_USERS { get; set; }
    }
}
