//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ECOMM_ORDER_ITEM
    {
        public long ORDER_ITEM_ID { get; set; }
        public long ORDER_ID { get; set; }
        public Nullable<long> PRODUCT_ID { get; set; }
        public Nullable<long> PRODUCT_QUANTITY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<decimal> PRODUCT_AMOUNT { get; set; }
    
        public virtual TB_ECOMM_PRODUCT TB_ECOMM_PRODUCT { get; set; }
        public virtual TB_ECOMM_ORDER TB_ECOMM_ORDER { get; set; }
    }
}
