//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ECOMM_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ECOMM_USERS()
        {
            this.TB_ECOMM_ADDRESS = new HashSet<TB_ECOMM_ADDRESS>();
            this.TB_ECOMM_CART_ITEM = new HashSet<TB_ECOMM_CART_ITEM>();
            this.TB_ECOMM_ORDER = new HashSet<TB_ECOMM_ORDER>();
        }
    
        public long USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_PASSWORD { get; set; }
        public string PASSWORD_SALT { get; set; }
        public string RESET_CODE { get; set; }
        public string USER_PROFILE_IMAGE { get; set; }
        public string USER_PHONE { get; set; }
        public Nullable<bool> EMAIL_CONFIRMED { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public Nullable<long> ROLE_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual TB_USERS_ROLES TB_USERS_ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ECOMM_ADDRESS> TB_ECOMM_ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ECOMM_CART_ITEM> TB_ECOMM_CART_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ECOMM_ORDER> TB_ECOMM_ORDER { get; set; }
    }
}
