//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ECOMM_PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ECOMM_PRODUCT()
        {
            this.TB_ECOMM_CART_ITEM = new HashSet<TB_ECOMM_CART_ITEM>();
            this.TB_ECOMM_ORDER_ITEM = new HashSet<TB_ECOMM_ORDER_ITEM>();
        }
    
        public long PRODUCT_ID { get; set; }
        public Nullable<long> SUB_CATEGORY_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public string PRODUCT_IMAGE1 { get; set; }
        public string PRODUCT_IMAGE2 { get; set; }
        public string PRODUCT_IMAGE3 { get; set; }
        public string PRODUCT_IMAGE4 { get; set; }
        public Nullable<decimal> PRODUCT_PRICE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual TB_ECOMM_SUB_CATEGORY TB_ECOMM_SUB_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ECOMM_CART_ITEM> TB_ECOMM_CART_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ECOMM_ORDER_ITEM> TB_ECOMM_ORDER_ITEM { get; set; }
    }
}
