//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ECOMM_SUB_CATEGORY
    {
        public long SUB_CATEGORY_ID { get; set; }
        public Nullable<long> CATEGORY_ID { get; set; }
        public string CATEGORY_NAME { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual TB_ECOMM_CATEGORY TB_ECOMM_CATEGORY { get; set; }
    }
}
