//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ECOMM_CART_ITEM
    {
        public long CART_ITEM_ID { get; set; }
        public Nullable<long> USER_ID { get; set; }
        public Nullable<long> PRODUCT_ID { get; set; }
        public Nullable<long> PRODUCT_DETAIL_ID { get; set; }
        public Nullable<int> CART_ITEM_QUANTITY { get; set; }
        public Nullable<decimal> CART_PRICE { get; set; }
        public Nullable<System.DateTime> ADDED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> CATEGORY_ID { get; set; }
        public Nullable<bool> WISHLIST { get; set; }
    
        public virtual TB_ECOMM_PRODUCT TB_ECOMM_PRODUCT { get; set; }
        public virtual TB_ECOMM_USERS TB_ECOMM_USERS { get; set; }
    }
}
