//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS_SHOP_Dev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RS_SHOP_Dev.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document presents the detail of the process and possible.
        /// </summary>
        internal static string Advantage_Document {
            get {
                return ResourceManager.GetString("Advantage_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LATEST EXPERIENCES.
        /// </summary>
        internal static string Advantage_Experience {
            get {
                return ResourceManager.GetString("Advantage_Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND YOUR FAVORITE PLAYER.
        /// </summary>
        internal static string Advantage_FindPalyer {
            get {
                return ResourceManager.GetString("Advantage_FindPalyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADVANTAGES.
        /// </summary>
        internal static string Advantage_Title {
            get {
                return ResourceManager.GetString("Advantage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under age of 14 years old user need parental authorization. Please complete all required fields.
        /// </summary>
        internal static string AgeValidationLabel {
            get {
                return ResourceManager.GetString("AgeValidationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to signup to enjoy all features of app.
        /// </summary>
        internal static string AuthMessage {
            get {
                return ResourceManager.GetString("AuthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        internal static string CartButtonConfirm {
            get {
                return ResourceManager.GetString("CartButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELIMINATE.
        /// </summary>
        internal static string CartButtonEliminate {
            get {
                return ResourceManager.GetString("CartButtonEliminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE FOR LATER.
        /// </summary>
        internal static string CartButtonSave {
            get {
                return ResourceManager.GetString("CartButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping :.
        /// </summary>
        internal static string CartLblShip {
            get {
                return ResourceManager.GetString("CartLblShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total :.
        /// </summary>
        internal static string CartLblSubTotal {
            get {
                return ResourceManager.GetString("CartLblSubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total :.
        /// </summary>
        internal static string CartLblTotal {
            get {
                return ResourceManager.GetString("CartLblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOPPING CART.
        /// </summary>
        internal static string CartTitle {
            get {
                return ResourceManager.GetString("CartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select City.
        /// </summary>
        internal static string EditCountryPop_CityAlert {
            get {
                return ResourceManager.GetString("EditCountryPop_CityAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Country.
        /// </summary>
        internal static string EditCountryPop_CountryAlert {
            get {
                return ResourceManager.GetString("EditCountryPop_CountryAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        internal static string Filter_ApplyButton {
            get {
                return ResourceManager.GetString("Filter_ApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE.
        /// </summary>
        internal static string Filter_Type {
            get {
                return ResourceManager.GetString("Filter_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTER.
        /// </summary>
        internal static string FilterHeader {
            get {
                return ResourceManager.GetString("FilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE RANGE.
        /// </summary>
        internal static string FilterPriceRange {
            get {
                return ResourceManager.GetString("FilterPriceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAYMENT DETAILS.
        /// </summary>
        internal static string FoodDrinkCheckout_PayDetails {
            get {
                return ResourceManager.GetString("FoodDrinkCheckout_PayDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Up at &quot;A&quot; Store.
        /// </summary>
        internal static string FoodDrinkCheckout_PickAstore {
            get {
                return ResourceManager.GetString("FoodDrinkCheckout_PickAstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Up at &quot;B&quot; Store.
        /// </summary>
        internal static string FoodDrinkCheckout_PickBstore {
            get {
                return ResourceManager.GetString("FoodDrinkCheckout_PickBstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Up at &quot;C&quot; Store.
        /// </summary>
        internal static string FoodDrinkCheckout_PickCstore {
            get {
                return ResourceManager.GetString("FoodDrinkCheckout_PickCstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up your order.
        /// </summary>
        internal static string FoodDrinkCheckout_PickOrder {
            get {
                return ResourceManager.GetString("FoodDrinkCheckout_PickOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string FoodDrinkCheckout_Total {
            get {
                return ResourceManager.GetString("FoodDrinkCheckout_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string FoodSearch {
            get {
                return ResourceManager.GetString("FoodSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not want to specify.
        /// </summary>
        internal static string Gender_Other {
            get {
                return ResourceManager.GetString("Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start.
        /// </summary>
        internal static string IntroButtonText {
            get {
                return ResourceManager.GetString("IntroButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum pain sit amet, consectetur adipisicing elit, sed do eiusmod..
        /// </summary>
        internal static string IntroDesc {
            get {
                return ResourceManager.GetString("IntroDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Title.
        /// </summary>
        internal static string IntroMainTitle {
            get {
                return ResourceManager.GetString("IntroMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Access.
        /// </summary>
        internal static string IntroSnackInternet {
            get {
                return ResourceManager.GetString("IntroSnackInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection.
        /// </summary>
        internal static string IntroSnackNoInternet {
            get {
                return ResourceManager.GetString("IntroSnackNoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONBOARDING.
        /// </summary>
        internal static string IntroTitle {
            get {
                return ResourceManager.GetString("IntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype Password.
        /// </summary>
        internal static string LoginConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        internal static string LoginContinue {
            get {
                return ResourceManager.GetString("LoginContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        internal static string LoginCreateAnAcoount {
            get {
                return ResourceManager.GetString("LoginCreateAnAcoount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email format.
        /// </summary>
        internal static string LoginEmailError {
            get {
                return ResourceManager.GetString("LoginEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginEmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGOT PASSWORD?.
        /// </summary>
        internal static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE AS A GUEST.
        /// </summary>
        internal static string LoginGuest {
            get {
                return ResourceManager.GetString("LoginGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string LoginNamePlaceholder {
            get {
                return ResourceManager.GetString("LoginNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium (1 day).
        /// </summary>
        internal static string MerchCheckout_1Day {
            get {
                return ResourceManager.GetString("MerchCheckout_1Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Express (2 days).
        /// </summary>
        internal static string MerchCheckout_2Days {
            get {
                return ResourceManager.GetString("MerchCheckout_2Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard (7 days).
        /// </summary>
        internal static string MerchCheckout_7Days {
            get {
                return ResourceManager.GetString("MerchCheckout_7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELIVERY.
        /// </summary>
        internal static string MerchCheckout_Delivery {
            get {
                return ResourceManager.GetString("MerchCheckout_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup at the store.
        /// </summary>
        internal static string MerchCheckout_PickStore {
            get {
                return ResourceManager.GetString("MerchCheckout_PickStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIPPING TO.
        /// </summary>
        internal static string MerchCheckout_ShipTo {
            get {
                return ResourceManager.GetString("MerchCheckout_ShipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET QR.
        /// </summary>
        internal static string OrderGetQR {
            get {
                return ResourceManager.GetString("OrderGetQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK STATUS.
        /// </summary>
        internal static string OrderPopup_CheckStatusButton {
            get {
                return ResourceManager.GetString("OrderPopup_CheckStatusButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEEP SHOPPING.
        /// </summary>
        internal static string OrderPopup_KeepShopButton {
            get {
                return ResourceManager.GetString("OrderPopup_KeepShopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weldone.
        /// </summary>
        internal static string OrderPopup_Weldone {
            get {
                return ResourceManager.GetString("OrderPopup_Weldone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRACKING.
        /// </summary>
        internal static string OrderTrack {
            get {
                return ResourceManager.GetString("OrderTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        internal static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethod.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred.
        /// </summary>
        internal static string Preferred {
            get {
                return ResourceManager.GetString("Preferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ProdDetailBtnBack {
            get {
                return ResourceManager.GetString("ProdDetailBtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD TO CART.
        /// </summary>
        internal static string ProdDetailBtnCart {
            get {
                return ResourceManager.GetString("ProdDetailBtnCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Shipping.
        /// </summary>
        internal static string ProdDetailFreeShip {
            get {
                return ResourceManager.GetString("ProdDetailFreeShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE.
        /// </summary>
        internal static string ProdDetailPrice {
            get {
                return ResourceManager.GetString("ProdDetailPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Profile_EditButton {
            get {
                return ResourceManager.GetString("Profile_EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Profile_NotificationButton {
            get {
                return ResourceManager.GetString("Profile_NotificationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Profile_OrdersButton {
            get {
                return ResourceManager.GetString("Profile_OrdersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string Profile_PayMethodButton {
            get {
                return ResourceManager.GetString("Profile_PayMethodButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions and Ans.
        /// </summary>
        internal static string Profile_QAButton {
            get {
                return ResourceManager.GetString("Profile_QAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string Profile_ShipAddressButton {
            get {
                return ResourceManager.GetString("Profile_ShipAddressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish List.
        /// </summary>
        internal static string Profile_WishListButton {
            get {
                return ResourceManager.GetString("Profile_WishListButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string ProfileBirthdayPlaceholder {
            get {
                return ResourceManager.GetString("ProfileBirthdayPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        internal static string ProfileContactPlaceholder {
            get {
                return ResourceManager.GetString("ProfileContactPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country/City.
        /// </summary>
        internal static string ProfileCountryPlaceholder {
            get {
                return ResourceManager.GetString("ProfileCountryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string ProfileGenderPlaceholder {
            get {
                return ResourceManager.GetString("ProfileGenderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string ProfilePhotoPlaceholder {
            get {
                return ResourceManager.GetString("ProfilePhotoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUPONS.
        /// </summary>
        internal static string Promotion_TabCoupons {
            get {
                return ResourceManager.GetString("Promotion_TabCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDERS.
        /// </summary>
        internal static string Promotion_TabOrder {
            get {
                return ResourceManager.GetString("Promotion_TabOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE AND EXP.
        /// </summary>
        internal static string Promotion_TabUseExp {
            get {
                return ResourceManager.GetString("Promotion_TabUseExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Settings_LangLabel {
            get {
                return ResourceManager.GetString("Settings_LangLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal Information.
        /// </summary>
        internal static string Settings_LegalInfoLabel {
            get {
                return ResourceManager.GetString("Settings_LegalInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Settings_NotificationLabel {
            get {
                return ResourceManager.GetString("Settings_NotificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Settings_OrderLabel {
            get {
                return ResourceManager.GetString("Settings_OrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string Settings_PrivacyLabel {
            get {
                return ResourceManager.GetString("Settings_PrivacyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Settings_ProfileLabel {
            get {
                return ResourceManager.GetString("Settings_ProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string Settings_SignoutButton {
            get {
                return ResourceManager.GetString("Settings_SignoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Location.
        /// </summary>
        internal static string Settings_SwitchGeo {
            get {
                return ResourceManager.GetString("Settings_SwitchGeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi Location.
        /// </summary>
        internal static string Settings_SwitchWifi {
            get {
                return ResourceManager.GetString("Settings_SwitchWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Settings_VersionLabel {
            get {
                return ResourceManager.GetString("Settings_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        internal static string Ship_AddAddress {
            get {
                return ResourceManager.GetString("Ship_AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Ship_Default {
            get {
                return ResourceManager.GetString("Ship_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping To.
        /// </summary>
        internal static string Ship_ShippingTo {
            get {
                return ResourceManager.GetString("Ship_ShippingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        internal static string ShippingAddress {
            get {
                return ResourceManager.GetString("ShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOOD &amp; DRINKS.
        /// </summary>
        internal static string ShopTitleFood {
            get {
                return ResourceManager.GetString("ShopTitleFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCHANDISE.
        /// </summary>
        internal static string ShopTitleMerch {
            get {
                return ResourceManager.GetString("ShopTitleMerch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TICKETS.
        /// </summary>
        internal static string ShopTitleTicket {
            get {
                return ResourceManager.GetString("ShopTitleTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Valid Date.
        /// </summary>
        internal static string Signup_DateAlert {
            get {
                return ResourceManager.GetString("Signup_DateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name and Parent ID Can&apos;t be Blank.
        /// </summary>
        internal static string Signup_ParentAlert {
            get {
                return ResourceManager.GetString("Signup_ParentAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SignupAuth {
            get {
                return ResourceManager.GetString("SignupAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I authorize the child&apos;s registartion.
        /// </summary>
        internal static string SignUpCondition_1 {
            get {
                return ResourceManager.GetString("SignUpCondition_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I authorize receivingcommunications from team or third parties.
        /// </summary>
        internal static string SignUpCondition_2 {
            get {
                return ResourceManager.GetString("SignUpCondition_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the conditions of the online fan data processing.
        /// </summary>
        internal static string SignUpCondition_3 {
            get {
                return ResourceManager.GetString("SignUpCondition_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string SignUpDOB {
            get {
                return ResourceManager.GetString("SignUpDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID.
        /// </summary>
        internal static string SignupParentIDPlaceholder {
            get {
                return ResourceManager.GetString("SignupParentIDPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Name.
        /// </summary>
        internal static string SignupParentNamePlaceholder {
            get {
                return ResourceManager.GetString("SignupParentNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNUP.
        /// </summary>
        internal static string SignupTitle {
            get {
                return ResourceManager.GetString("SignupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Wallet_Date {
            get {
                return ResourceManager.GetString("Wallet_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Wallet_Order {
            get {
                return ResourceManager.GetString("Wallet_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pickup at.
        /// </summary>
        internal static string Wallet_PickupAt {
            get {
                return ResourceManager.GetString("Wallet_PickupAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Wallet_Time {
            get {
                return ResourceManager.GetString("Wallet_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        internal static string Wallet_Title {
            get {
                return ResourceManager.GetString("Wallet_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string Wallet_User {
            get {
                return ResourceManager.GetString("Wallet_User", resourceCulture);
            }
        }
    }
}
